import { Event } from '@/types/event';

export const mockEvents: Event[] = [
  {
    id: '1',
    type: 'stage',
    title: 'Stage dressage intensif avec cavalerie',
    slug: 'stage-dressage-intensif',
    description: 'Un stage de perfectionnement avec une cavalerie adaptée à tous les niveaux.',
    discipline: 'Dressage',
    niveau: 'Intermédiaire',
    age_group: 'Adulte',
    start_date: '2024-09-10',
    end_date: '2024-09-12',
    price_min: 320,
    price_max: 420,
    region: 'Île-de-France',
    location: 'Chantilly',
    lat: 49.19,
    lng: 2.48,
    horses_provided: true,
    accommodation: true,
    organizer_id: 'org-1',
    premium_until: '2024-12-01T00:00:00Z',
    status: 'published',
    created_at: '2024-07-01T12:00:00Z',
    coverImage: 'https://images.unsplash.com/photo-1516893844737-64b4618f0cde',
  },
  {
    id: '2',
    type: 'rando',
    title: 'Rando plage et forêt - Côte Atlantique',
    slug: 'rando-plage-foret',
    description: 'Trois jours de randonnée entre plages et forêts, hébergement inclus.',
    discipline: 'Extérieur',
    niveau: 'Tous niveaux',
    age_group: 'Famille',
    start_date: '2024-08-18',
    end_date: '2024-08-20',
    price_min: 260,
    price_max: 260,
    region: 'Nouvelle-Aquitaine',
    location: 'Lacanau',
    lat: 44.98,
    lng: -1.07,
    horses_provided: true,
    accommodation: true,
    organizer_id: 'org-2',
    premium_until: null,
    status: 'published',
    created_at: '2024-06-20T12:00:00Z',
    coverImage: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef',
  },
  {
    id: '3',
    type: 'concours',
    title: 'Concours CSO Amateur 1',
    slug: 'concours-cso-amateur-1',
    description: 'Concours de saut d’obstacles pour cavaliers amateurs, dotation en matériel.',
    discipline: 'CSO',
    niveau: 'Confirmé',
    age_group: 'Adulte',
    start_date: '2024-09-22',
    end_date: '2024-09-22',
    price_min: 45,
    price_max: 45,
    region: 'Auvergne-Rhône-Alpes',
    location: 'Chambéry',
    lat: 45.57,
    lng: 5.91,
    horses_provided: false,
    accommodation: false,
    organizer_id: 'org-3',
    premium_until: null,
    status: 'published',
    created_at: '2024-06-28T12:00:00Z',
    coverImage: 'https://images.unsplash.com/photo-1509043759401-136742328bb3',
  },
];
